### PR TITLE
Setup Library with new Synfrastructure

### PR DESCRIPTION
**Pull request by synbot**
### Acceptance Criteria
1. App dev environment works
2. Readme is updated
3. Synfrastructure is included

### CODE REVIEW

**Comment by kylecesmat** [comment]
:m: :star2:

**Comment by natestormer** [comment]
:recycle:

**Comment by kylecesmat** [comment]
:recycle: :star2:

**Comment by natestormer** [comment]
:hand:

**Comment by natestormer** [comment]
:+1:

**Pull request merged**
